spring:
  application:
    name: ChatApp
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
    livereload:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/chatapp
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  mail:
      host: sandbox.smtp.mailtrap.io
      port: 2525
      username: 31fff8a546f228
      password: b3aebdccd67bbc
      properties:
        mail:
          smtp:
            auth: false
            starttls:
              enable: false
